//! Snapshot a workspace's current state as a fully-pinned manifest.
//!
//! Each repo emerges with its current HEAD sha as its `revision`, so the
//! manifest can be re-applied later (e.g. for release tagging or bug
//! reproduction) to get exactly the same on-disk state back.

use serde::Serialize;

use crate::error::{Error, Result};
use crate::git;
use crate::manifest::DEFAULT_REMOTE;
use crate::workspace::Workspace;

/// Produce a frozen manifest as TOML text.
pub fn freeze(workspace: &Workspace) -> Result<String> {
    let manifest = workspace.load_manifest()?;
    let repos = manifest.resolve()?;

    let mut frozen = Frozen {
        version: 1,
        repos: Vec::with_capacity(repos.len()),
    };

    for repo in &repos {
        let abs = workspace.repo_path(&repo.path);
        if !abs.exists() {
            return Err(Error::FreezeUnavailable {
                name: repo.name.clone(),
                reason: "is not cloned".into(),
            });
        }
        if !git::local::is_repo(&abs) {
            return Err(Error::FreezeUnavailable {
                name: repo.name.clone(),
                reason: "path exists but is not a git repository".into(),
            });
        }
        let sha = git::local::head_sha(&abs)?;

        // Only emit path/remote if they differ from the per-repo default
        // (path = repo.name, remote = "origin").
        let path = if repo.path.as_path() == std::path::Path::new(&repo.name) {
            None
        } else {
            Some(repo.path.display().to_string())
        };
        let remote = if repo.remote == DEFAULT_REMOTE {
            None
        } else {
            Some(repo.remote.clone())
        };

        frozen.repos.push(FrozenRepo {
            name: repo.name.clone(),
            url: repo.url.clone(),
            revision: sha,
            path,
            remote,
            groups: repo.groups.clone(),
        });
    }

    let body = toml::to_string(&frozen).map_err(|e| Error::ManifestSerialize(e.to_string()))?;
    Ok(format!(
        "# Generated by `gasp freeze`. Each repo is pinned to the sha\n\
         # currently checked out in the workspace at freeze time.\n\
         {body}"
    ))
}

#[derive(Serialize)]
struct Frozen {
    version: u32,
    #[serde(rename = "repos")]
    repos: Vec<FrozenRepo>,
}

#[derive(Serialize)]
struct FrozenRepo {
    name: String,
    url: String,
    revision: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    remote: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    groups: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::Manifest;
    use std::path::Path;
    use std::process::Command;

    fn run(cwd: &Path, args: &[&str]) {
        let s = Command::new("git")
            .args(args)
            .current_dir(cwd)
            .status()
            .unwrap();
        assert!(s.success(), "git {args:?} failed");
    }

    fn fixture() -> (tempfile::TempDir, Workspace) {
        let root = tempfile::tempdir().unwrap();
        let src = root.path().join("src");
        let bare = root.path().join("r.git");
        std::fs::create_dir_all(&src).unwrap();
        run(&src, &["init", "-q", "-b", "main", "."]);
        std::fs::write(src.join("f"), "1\n").unwrap();
        run(&src, &["add", "-A"]);
        run(
            &src,
            &[
                "-c",
                "user.email=t@t",
                "-c",
                "user.name=t",
                "commit",
                "-q",
                "-m",
                "c1",
            ],
        );
        run(
            root.path(),
            &[
                "clone",
                "--bare",
                "-q",
                src.to_str().unwrap(),
                bare.to_str().unwrap(),
            ],
        );

        let ws_root = root.path().join("ws");
        std::fs::create_dir(&ws_root).unwrap();
        let seed = ws_root.join("seed.toml");
        std::fs::write(
            &seed,
            format!(
                "version = 1\n[[repos]]\nname = \"r\"\nurl = \"{}\"\nrevision = \"main\"\n",
                bare.display()
            ),
        )
        .unwrap();
        let ws = Workspace::init(&ws_root, &seed).unwrap();

        // Clone the bare into the workspace so the repo exists at <ws>/r.
        run(
            &ws_root,
            &[
                "clone",
                "-q",
                bare.to_str().unwrap(),
                ws_root.join("r").to_str().unwrap(),
            ],
        );

        (root, ws)
    }

    #[test]
    fn freeze_pins_current_sha_and_round_trips() {
        let (_root, ws) = fixture();
        let frozen_text = freeze(&ws).unwrap();

        assert!(frozen_text.contains("Generated by"));
        assert!(frozen_text.contains("version = 1"));
        assert!(frozen_text.contains("name = \"r\""));
        // The frozen revision should be a 40-char sha, not "main".
        let head = git::local::head_sha(&ws.repo_path(std::path::Path::new("r"))).unwrap();
        assert!(frozen_text.contains(&head));
        assert!(!frozen_text.contains("revision = \"main\""));

        // Round-trip: the output is a valid manifest.
        let parsed = Manifest::from_str_at(&frozen_text, Path::new("frozen.toml")).unwrap();
        assert_eq!(parsed.repos.len(), 1);
        assert_eq!(parsed.repos[0].revision.as_deref(), Some(head.as_str()));
    }

    #[test]
    fn freeze_errors_on_missing_repo() {
        let (_root, ws) = fixture();
        std::fs::remove_dir_all(ws.repo_path(std::path::Path::new("r"))).unwrap();
        let err = freeze(&ws).unwrap_err();
        assert!(matches!(err, Error::FreezeUnavailable { ref name, .. } if name == "r"));
    }
}
